# -*- coding: utf-8 -*-
"""Aimbot detection

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DzSkYlC0TbmJtUrNzX1B64U5u_r08E3r
"""

from google.colab import drive
drive.mount('/content/drive')

#!pip install pydrive

import os

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth=GoogleAuth()

gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

fileId = drive.CreateFile({'id': '1kzauog3ER-eevEVkmUn1k5sil0oJgWT0'}) #DRIVE_FILE_ID is file id example: 1iytA1n2z4go3uVCwE_vIKouTKyIDjEq  # folder_data.zip
fileId.GetContentFile('data')  # Save Drive file as a local file

import pandas as pd
data=pd.read_csv('data.csv')

X=data.iloc[:,0:14]
Y=data['isHacker']

data.dtypes

from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

dtc=DecisionTreeClassifier(random_state=0)
parameters={'max_depth':range(3,20)}
model=GridSearchCV(estimator=dtc,param_grid=parameters,cv=10,n_jobs=4)

model.fit(X,Y)
print(model.best_score_,model.best_params_)

fileId = drive.CreateFile({'id': '1vVVBFcREZ3d4FX-S_KMuwvlZe6lg5AC0'}) #DRIVE_FILE_ID is file id example: 1iytA1n2z4go3uVCwE_vIKouTKyIDjEq  # folder_data.zip
fileId.GetContentFile('test.csv')  # Save Drive file as a local file

#!ls

test=pd.read_csv('test.csv')
X_test=test.iloc[:,0:14]
Y_test=test['isHacker']
Y_predict=model.predict(X_test)
matrix=confusion_matrix(Y_predict,Y_test)
Y_predict


